name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run Docker container
      uses: actions/docker/cli@v1
      with:
        args: build -t my-image .
      shell: bash
    - name: Run tests
      uses: actions/docker/cli@v1
      with:
        args: run my-image npm test
